[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sbrsol"
authors = [{name = "saberhq", email = "cui@saberhq"}]
dynamic = ["version", "description"]
